# Generated by Django 5.1 on 2024-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
