# Generated by Django 5.1 on 2024-09-19 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(default='', upload_to='shop')),
                ('quantity', models.IntegerField()),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('username', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
